### ISSUE TITLE
Redundent space in the file name style of the sharer's direction page

### ISSUE THREAD

**Issue by chenw23** [fdu-cooks/fdu-gradhotpot#1]
In the mark down page of the sharer's direction page (line 46) [https://github.com/StrayBird-ATSH/fdu-gradhotpot/blame/master/_posts/Hotpot建站/2019-04-13-howtoshare.md#L46](url), whether there should be spaces between date and tile is not consistent with the actual filename. 
Please consider improve this detail. 
Thanks

**Comment by AaronHeee** [comment]
Thanks for your advice. We'll correct it ASAP. 
Btw, we move our website to [fdu-hotpot.top](http://fdu-hotpot.top/), you can find the newest version of sharing guide [here](http://fdu-hotpot.top/?p=98).
