### ISSUE TITLE
Consider utterance instead of disqus

### ISSUE THREAD

**Issue by Ir1d** [fdu-cooks/fdu-gradhotpot#2]
Disqus 被墙了（摊手

utterance: https://github.com/utterance/utterances

**Comment by AaronHeee** [comment]
我们已经把网站迁移到 [fdu-hotpot.top](http://fdu-hotpot.top/) 啦，可以用复旦学邮+邀请码注册，不用担心被墙，大概4月20日会进行公测，敬请期待！
